// This file is normally generated by the render-wasm Emscripten build
// (copy_shared_artifact step). It is reconstructed here from the Rust source
// enum definitions in render-wasm/src/wasm/**/*.rs so that the ClojureScript
// compiler can resolve the JS dependency without requiring Emscripten locally.
//
// Every constant corresponds 1-to-1 with a Rust #[repr(u8)] enum variant.
// DO NOT edit manually — regenerate from Rust sources if enums change.

// blurs.rs — RawBlurType
export const RawBlurType = Object.freeze({
  LayerBlur: 0,
  BackgroundBlur: 1,
});

// blend.rs — RawBlendMode
export const RawBlendMode = Object.freeze({
  Normal: 3,
  Screen: 14,
  Overlay: 15,
  Darken: 16,
  Lighten: 17,
  ColorDodge: 18,
  ColorBurn: 19,
  HardLight: 20,
  SoftLight: 21,
  Difference: 22,
  Exclusion: 23,
  Multiply: 24,
  Hue: 25,
  Saturation: 26,
  Color: 27,
  Luminosity: 28,
});

// paths/bools.rs — RawBoolType
export const RawBoolType = Object.freeze({
  Union: 0,
  Difference: 1,
  Intersection: 2,
  Exclude: 3,
});

// shapes/mod.rs — RawShapeType
export const RawShapeType = Object.freeze({
  Frame: 0,
  Group: 1,
  Bool: 2,
  Rect: 3,
  Path: 4,
  Text: 5,
  Circle: 6,
  SVGRaw: 7,
});

// shadows.rs — RawShadowStyle
export const RawShadowStyle = Object.freeze({
  DropShadow: 0,
  InnerShadow: 1,
});

// strokes.rs — RawStrokeStyle
export const RawStrokeStyle = Object.freeze({
  Solid: 0,
  Dotted: 1,
  Dashed: 2,
  Mixed: 3,
});

// strokes.rs — RawStrokeCap
export const RawStrokeCap = Object.freeze({
  None: 0,
  LineArrow: 1,
  TriangleArrow: 2,
  SquareMarker: 3,
  CircleMarker: 4,
  DiamondMarker: 5,
  Round: 6,
  Square: 7,
});

// svg_attrs.rs — RawStrokeLineCap
export const RawStrokeLineCap = Object.freeze({
  Butt: 0,
  Round: 1,
  Square: 2,
});

// svg_attrs.rs — RawStrokeLineJoin
export const RawStrokeLineJoin = Object.freeze({
  Miter: 0,
  Round: 1,
  Bevel: 2,
});

// svg_attrs.rs — RawFillRule
export const RawFillRule = Object.freeze({
  Nonzero: 0,
  Evenodd: 1,
});

// fonts.rs — RawFontStyle
export const RawFontStyle = Object.freeze({
  Normal: 0,
  Italic: 1,
});

// text.rs — RawTextAlign
export const RawTextAlign = Object.freeze({
  Left: 0,
  Center: 1,
  Right: 2,
  Justify: 3,
});

// text.rs — RawTextDirection
export const RawTextDirection = Object.freeze({
  Ltr: 0,
  Rtl: 1,
});

// text.rs — RawTextDecoration
export const RawTextDecoration = Object.freeze({
  None: 0,
  Underline: 1,
  LineThrough: 2,
  Overline: 3,
});

// text.rs — RawTextTransform
export const RawTextTransform = Object.freeze({
  None: 0,
  Uppercase: 1,
  Lowercase: 2,
  Capitalize: 3,
});

// text.rs — RawGrowType
export const RawGrowType = Object.freeze({
  Fixed: 0,
  AutoWidth: 1,
  AutoHeight: 2,
});

// layouts/align.rs — RawAlignItems
export const RawAlignItems = Object.freeze({
  Start: 0,
  End: 1,
  Center: 2,
  Stretch: 3,
});

// layouts/align.rs — RawAlignContent
export const RawAlignContent = Object.freeze({
  Start: 0,
  End: 1,
  Center: 2,
  SpaceBetween: 3,
  SpaceAround: 4,
  SpaceEvenly: 5,
  Stretch: 6,
});

// layouts/align.rs — RawJustifyItems
export const RawJustifyItems = Object.freeze({
  Start: 0,
  End: 1,
  Center: 2,
  Stretch: 3,
});

// layouts/align.rs — RawJustifyContent
export const RawJustifyContent = Object.freeze({
  Start: 0,
  End: 1,
  Center: 2,
  SpaceBetween: 3,
  SpaceAround: 4,
  SpaceEvenly: 5,
  Stretch: 6,
});

// layouts/align.rs — RawJustifySelf
export const RawJustifySelf = Object.freeze({
  None: 0,
  Auto: 1,
  Start: 2,
  End: 3,
  Center: 4,
  Stretch: 5,
});

// layouts/align.rs — RawAlignSelf
export const RawAlignSelf = Object.freeze({
  None: 0,
  Auto: 1,
  Start: 2,
  End: 3,
  Center: 4,
  Stretch: 5,
});

// layouts/align.rs — RawVerticalAlign
export const RawVerticalAlign = Object.freeze({
  Top: 0,
  Center: 1,
  Bottom: 2,
});

// layouts/flex.rs — RawFlexDirection
export const RawFlexDirection = Object.freeze({
  Row: 0,
  RowReverse: 1,
  Column: 2,
  ColumnReverse: 3,
});

// layouts/flex.rs — RawWrapType
export const RawWrapType = Object.freeze({
  Wrap: 0,
  Nowrap: 1,
});

// layouts/grid.rs — RawGridDirection
export const RawGridDirection = Object.freeze({
  Row: 0,
  Column: 1,
});

// layouts/grid.rs — RawGridTrackType
export const RawGridTrackType = Object.freeze({
  Percent: 0,
  Flex: 1,
  Auto: 2,
  Fixed: 3,
});

// layouts/constraints.rs — RawConstraintH
export const RawConstraintH = Object.freeze({
  Left: 0,
  Right: 1,
  Leftright: 2,
  Center: 3,
  Scale: 4,
});

// layouts/constraints.rs — RawConstraintV
export const RawConstraintV = Object.freeze({
  Top: 0,
  Bottom: 1,
  Topbottom: 2,
  Center: 3,
  Scale: 4,
});

// layouts.rs — RawSizing
export const RawSizing = Object.freeze({
  Fill: 0,
  Fix: 1,
  Auto: 2,
});

// transforms.rs — RawTransformEntryKind
export const RawTransformEntryKind = Object.freeze({
  Parent: 0,
  Child: 1,
});

// fills.rs — RawFillData (discriminant values for the C tagged union)
export const RawFillData = Object.freeze({
  Solid: 0x00,
  Linear: 0x01,
  Radial: 0x02,
  Image: 0x03,
});

// paths.rs — RawSegmentData (discriminant values)
export const RawSegmentData = Object.freeze({
  MoveTo: 0x01,
  LineTo: 0x02,
  CurveTo: 0x03,
  Close: 0x04,
});
